### PR TITLE
make the template runnable and clean from useless options

### PR DESCRIPTION
**Pull request by marcobarilari**
I have add some code to make it display something (the fixation cross) and deleted the option from the localizers. I think that having a clean one (instead with the options from the localizer) is better, users can be sent to see the localizers repo to have a complex example on how to develop a full experiment.

### CODE REVIEW

**Review by Remi-Gau — COMMENTED** [review]
@marcobarilari 

What are the updates of the submodules exactly?

**Comment by Remi-Gau** [comment]
> @marcobarilari
> 
> What are the updates of the submodules exactly?

Ah I see. It seems the upstream repo was already tracking the latest tagged version of the submodules but this PR brings them back to an earlier version. Let me change that.

**Comment by marcobarilari** [comment]
ups, my bad then :)

**Comment by Remi-Gau** [comment]
> ups, my bad then :)

no worries.

sub-modules are confusing...

**Review by Remi-Gau — APPROVED** [review]

**Comment by Remi-Gau** [comment]
Good to me

**Pull request merged**
